version: '3.8'
services:
  app:
    build: .
    image: propiedad-direct-app:latest
    container_name: propiedad-direct-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/propiedad-direct
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin

  db:
    image: postgres:latest
    container_name: propiedad-direct-db
    environment:
      POSTGRES_DB: propiedad-direct
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
