apiVersion: v1
kind: Service
metadata:
  name: propiedad-direct-app
spec:
  selector:
    app: propiedad-direct-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
