apiVersion: v1
kind: Service
metadata:
  name: propiedad-direct-db
spec:
  selector:
    app: propiedad-direct-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
